/**
 * Every request goes through the Gateway — never straight to auth-service or
 * jobs-service, which aren't meant to be reachable from a browser at all
 * (docs/ARCHITECTURE.md).
 *
 * `credentials: "include"` is the single line that makes cookie auth work: without it
 * the browser won't send the httpOnly access_token/refresh_token cookies cross-origin
 * (frontend on :3000, gateway on :8000).
 */
const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000/api";

export class ApiError extends Error {
  status: number;
  constructor(status: number, message: string) {
    super(message);
    this.status = status;
  }
}

/**
 * Silent token refresh.
 *
 * Access tokens deliberately live only 15 minutes (see docs/AUTH_AND_SECURITY.md) — a
 * stolen one expires fast. The cost is that every session breaks after 15 minutes unless
 * something renews it, which is what this does: on a 401, call /auth/refresh once and
 * replay the original request. The user never notices.
 *
 * The shared promise matters. A page like /applications fires several requests at once;
 * without it, each 401 would start its own refresh, and because refresh ROTATES the token,
 * the second call would present a token the first had already invalidated — logging the
 * user out precisely because the rotation security worked. One in-flight refresh, everyone
 * awaits it.
 */
// Exactly these four, matched EXACTLY — not a `/auth/` prefix check. Prefix matching
// looked right and was wrong: it also excluded /auth/google/status and /auth/google/connect,
// which are ordinary protected endpoints that should refresh like any other.
const NO_REFRESH_RETRY = new Set([
  "/auth/login",    // a bad password must surface as a bad password
  "/auth/signup",
  "/auth/refresh",  // retrying refresh on 401 would loop forever
  "/auth/logout",
]);

let refreshInFlight: Promise<boolean> | null = null;

async function refreshSession(): Promise<boolean> {
  if (!refreshInFlight) {
    refreshInFlight = fetch(`${API_BASE_URL}/auth/refresh`, {
      method: "POST",
      credentials: "include",
    })
      .then((r) => r.ok)
      .catch(() => false)
      .finally(() => {
        refreshInFlight = null;
      });
  }
  return refreshInFlight;
}

/** For non-JSON endpoints (file upload, PDF download) that can't go through request(),
 *  but still need the same silent-refresh behaviour. */
async function rawFetch(url: string, options: RequestInit): Promise<Response> {
  let res = await fetch(url, options);
  if (res.status === 401 && (await refreshSession())) {
    res = await fetch(url, options);
  }
  return res;
}

async function request<T>(path: string, options: RequestInit = {}, retry = true): Promise<T> {
  const res = await fetch(`${API_BASE_URL}${path}`, {
    ...options,
    credentials: "include",
    headers: { "Content-Type": "application/json", ...options.headers },
  });

  if (res.status === 401 && retry && !NO_REFRESH_RETRY.has(path)) {
    if (await refreshSession()) {
      return request<T>(path, options, false);
    }
  }

  if (!res.ok) {
    const body = await res.json().catch(() => ({ detail: res.statusText }));
    const detail =
      typeof body.detail === "string" ? body.detail : JSON.stringify(body.detail ?? body);
    throw new ApiError(res.status, detail);
  }

  return res.status === 204 ? (undefined as T) : res.json();
}

export interface User {
  id: string;
  email: string;
  role: string;
}

export interface AppNotification {
  id: string;
  kind: string;
  title: string;
  body: string | null;
  link: string | null;
  posting_id: string | null;
  read: boolean;
  created_at: string;
}

export interface Profile {
  user_id: string;
  full_name: string | null;
  headline: string | null;
  skills: string | null;
  target_roles: string | null;
  countries: string;
  preferred_locations: string | null;
  remote_only: boolean;
  min_salary: number | null;
  seniority: string | null;
  resume_text: string | null;
}

export interface Job {
  posting_id: string;
  title: string;
  company_name: string | null;
  location: string | null;
  region: string | null;
  seniority: string | null;
  remote: boolean;
  salary: number | null;
  posted_month: number | null;
  required_skills?: string[];
  /** Spark MLlib output, joined in by dbt — what the model thinks this role should pay
   *  and how far the advertised salary sits from that. */
  predicted_salary?: number | null;
  salary_vs_market?: number | null;
  pay_band?: string | null;
  /** Provenance. `true` = a live posting fetched from a job board (Adzuna/Remotive) with
   *  a `url` you can apply through; `false` = generated by the synthetic pipeline. */
  is_real?: boolean;
  source?: string | null;
  url?: string | null;
}

export interface ToolCall {
  tool: string;
  arguments: Record<string, unknown>;
  result_preview: string;
}

export interface Delegation {
  agent: string;
  question: string;
  answer: string;
  tools_used: string[];
}

export interface AgentAnswer {
  /** explicit = you named the agent · routed = planner picked ONE ·
   *  orchestrated = orchestrator combined SEVERAL */
  mode?: string;
  agent: string;
  routing_reason?: string;
  answer: string;
  tool_calls: ToolCall[];
  delegations?: Delegation[];
  iterations: number;
  stopped_early: boolean;
}

export interface Application {
  id: string;
  company: string;
  role: string | null;
  posting_id: string | null;
  status: string;
  resume_version: string | null;
  source: string;
  applied_at: string;
  updated_at: string;
}

export interface FunnelResponse {
  total_applications: number;
  rejected: number;
  awaiting_response: number;
  stages: { stage: string; count: number; percent_of_applied: number }[];
}

export interface ResumePerformance {
  resume_version: string;
  applications: number;
  positive_responses: number;
  response_rate_percent: number;
  sample_warning: string | null;
}

export interface GmailStatus {
  configured: boolean;
  connected: boolean;
  google_email?: string | null;
  last_synced_at?: string | null;
  message?: string;
}

export interface ResumeVersion {
  id: string;
  label: string;
  source_format: string;
  origin: string;
  is_active: boolean;
  has_latex: boolean;
  tailored_for_posting_id: string | null;
  change_summary: string | null;
  created_at: string;
  preview: string;
}

export interface ActiveResume {
  exists: boolean;
  id?: string;
  label?: string;
  content_text: string;
  content_latex: string | null;
  source_format?: string;
  /** true when the active version was uploaded as a PDF and we kept the original bytes,
   *  so the preview can show the REAL document instead of extracted text. */
  has_original_pdf?: boolean;
}

export const api = {
  // ---- auth ----
  signup: (email: string, password: string) =>
    request<User>("/auth/signup", { method: "POST", body: JSON.stringify({ email, password }) }),
  login: (email: string, password: string) =>
    request<User>("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }),
  logout: () => request<void>("/auth/logout", { method: "POST" }),
  me: () => request<User>("/auth/me"),

  // ---- profile ----
  // ---- notifications (the bell) ----
  listNotifications: () => request<AppNotification[]>("/notifications?limit=30"),
  unreadCount: () => request<{ unread: number }>("/notifications/unread-count"),
  markAllRead: () => request<{ marked_read: number }>("/notifications/read-all", { method: "POST" }),
  markRead: (id: string) =>
    request<AppNotification>(`/notifications/${id}/read`, { method: "POST" }),

  getProfile: () => request<Profile>("/profile"),
  /** Read the active resume and return the profile fields it implies. Returns a
   *  SUGGESTION — the caller shows it for review; nothing is saved until the user saves. */
  profileFromResume: () =>
    request<{
      source_version: string;
      suggestion: Partial<Record<keyof Profile, string | null>>;
    }>("/profile/from-resume", { method: "POST" }),
  updateProfile: (patch: Partial<Profile>) =>
    request<Profile>("/profile", { method: "PATCH", body: JSON.stringify(patch) }),

  // ---- jobs ----
  searchJobs: (params: Record<string, string | number | boolean | undefined>) => {
    const query = new URLSearchParams();
    Object.entries(params).forEach(([k, v]) => {
      if (v !== undefined && v !== "" && v !== false) query.set(k, String(v));
    });
    return request<{ total: number; limit: number; offset: number; jobs: Job[] }>(
      `/jobs/search?${query}`
    );
  },
  getJob: (postingId: string) => request<Job>(`/jobs/${postingId}`),
  jobFilters: () =>
    request<{
      skills: string[];
      regions: string[];
      seniorities: string[];
      pay_bands: string[];
      source_counts?: { real?: number; synthetic?: number };
    }>("/jobs/filters"),

  // ---- analytics ----
  analytics: <T>(metric: string) => request<T>(`/analytics/${metric}`),

  // ---- applications & Gmail ----
  listApplications: () => request<Application[]>("/applications"),
  createApplication: (body: {
    company: string; role?: string; status?: string; resume_version?: string; posting_id?: string;
  }) => request<Application>("/applications", { method: "POST", body: JSON.stringify(body) }),
  updateApplication: (id: string, patch: { status?: string; role?: string; resume_version?: string }) =>
    request<Application>(`/applications/${id}`, { method: "PATCH", body: JSON.stringify(patch) }),
  funnel: () => request<FunnelResponse>("/applications/funnel"),
  resumePerformance: () => request<ResumePerformance[]>("/applications/resume-performance"),
  syncInbox: () => request<{ queued: boolean; task_id: string }>("/applications/sync-inbox", { method: "POST" }),
  syncStatus: (taskId: string) => request<{ status: string; count?: number; error?: string }>(`/applications/sync-status/${taskId}`),
  gmailStatus: () => request<GmailStatus>("/auth/google/status"),
  gmailConnect: () => request<{ authorization_url: string }>("/auth/google/connect"),

  // ---- resume ----
  getActiveResume: () => request<ActiveResume>("/resume/active"),
  listResumeVersions: () => request<ResumeVersion[]>("/resume/versions"),
  saveResume: (content_text: string, content_latex: string | null, label?: string) =>
    request<ResumeVersion>("/resume/save", {
      method: "POST",
      body: JSON.stringify({ content_text, content_latex, label }),
    }),
  activateResumeVersion: (id: string) =>
    request<ResumeVersion>(`/resume/versions/${id}/activate`, { method: "POST" }),
  deleteResumeVersion: (id: string) =>
    request<{ deleted: boolean; label: string }>(`/resume/versions/${id}`, { method: "DELETE" }),

  uploadResume: async (file: File): Promise<ResumeVersion> => {
    const form = new FormData();
    form.append("file", file);
    // No Content-Type header on purpose: the browser must set it itself so it can add
    // the multipart boundary. Setting it manually is the classic broken-upload bug.
    //
    // rawFetch (not request) because request() JSON-encodes; but it still needs the same
    // 401 -> refresh -> retry, or an upload started 15 minutes into a session just fails.
    const res = await rawFetch(`${API_BASE_URL}/resume/upload`, {
      method: "POST",
      credentials: "include",
      body: form,
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({ detail: res.statusText }));
      throw new ApiError(res.status, typeof body.detail === "string" ? body.detail : "Upload failed");
    }
    return res.json();
  },

  downloadResumeUrl: (fmt: "tex" | "txt" | "pdf") => `${API_BASE_URL}/resume/download?fmt=${fmt}`,

  /** Fetch the compiled PDF as a blob URL for in-page preview.
   *  A plain <iframe src="/resume/download?fmt=pdf"> would NOT work: the iframe request
   *  is a top-level navigation the browser makes without our credentials:"include"
   *  setting, so the auth cookie wouldn't be attached and the gateway would 401. Fetching
   *  it ourselves and handing the iframe a blob: URL keeps the request authenticated. */
  previewResumePdf: async (): Promise<string> => {
    const res = await rawFetch(`${API_BASE_URL}/resume/download?fmt=pdf`, {
      credentials: "include",
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({ detail: res.statusText }));
      throw new ApiError(res.status, typeof body.detail === "string" ? body.detail : "Preview failed");
    }
    return URL.createObjectURL(await res.blob());
  },

  // ---- agents ----
  listAgents: () =>
    request<Record<string, { description: string; tools: string[] }>>("/agents"),
  ask: (message: string, agent?: string, mode: "auto" | "orchestrate" = "auto") =>
    request<AgentAnswer>("/agents/ask", {
      method: "POST",
      body: JSON.stringify({ message, agent: agent || null, mode }),
    }),
};
